In [7]:
import numpy as np

x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [12]:
y=np.array([1,2,3,4], ndmin=10)
print(y)
print(y.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [16]:
#https://www.youtube.com/watch?v=CoS0L_UtkMo&list=PLjVLYmrlmjGfgBKkIFBkMNGG7qyRfo00W&index=4
z=np.zeros((3,4))
print(z)
print(z.ndim)
#np.ones()
em = np.empty((3)) # the elements will be previus memory data
print(em)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
[5.05016505e-310 0.00000000e+000 0.00000000e+000]
